-- =============================================================================
-- Vidyavani — Seed Data
-- Real NSQF IT/ITES sector data (sourced from NASSCOM SSC public documents)
-- Plus career metadata and sample job postings
-- =============================================================================

-- =============================================================================
-- NSQF Sectors
-- =============================================================================

INSERT INTO nsqf_sectors (id, code, name, description) VALUES
  ('a1000000-0000-0000-0000-000000000001', 'IT-ITES',     'Information Technology & IT Enabled Services', 'Covers software development, BPO, data science, cloud, and cybersecurity'),
  ('a1000000-0000-0000-0000-000000000002', 'HEALTHCARE',  'Healthcare & Life Sciences',                   'Covers nursing, lab technology, hospital management'),
  ('a1000000-0000-0000-0000-000000000003', 'BFSI',        'Banking, Financial Services & Insurance',      'Covers banking operations, insurance, fintech'),
  ('a1000000-0000-0000-0000-000000000004', 'LOGISTICS',   'Logistics, Retail & E-Commerce',               'Covers supply chain, warehouse, last-mile delivery'),
  ('a1000000-0000-0000-0000-000000000005', 'MANUFACTURING','Manufacturing & Capital Goods',                'Covers CNC, welding, quality control');

-- =============================================================================
-- NSQF IT/ITES Courses (Level 4 and Level 5)
-- Source: NASSCOM SSC Qualification Pack documents
-- =============================================================================

INSERT INTO nsqf_courses (id, sector_id, code, name, nsqf_level, duration_hrs, description, source_url) VALUES
  ('b1000000-0000-0000-0000-000000000001', 'a1000000-0000-0000-0000-000000000001',
   'SSC/Q0101', 'Junior Software Developer',          4, 400,
   'Entry-level software development covering basic programming, web fundamentals, and version control',
   'https://www.nasscom.in/ssc-qp'),

  ('b1000000-0000-0000-0000-000000000002', 'a1000000-0000-0000-0000-000000000001',
   'SSC/Q0102', 'Software Developer',                 5, 600,
   'Full-stack web development, databases, REST APIs, and agile methodologies',
   'https://www.nasscom.in/ssc-qp'),

  ('b1000000-0000-0000-0000-000000000003', 'a1000000-0000-0000-0000-000000000001',
   'SSC/Q0501', 'Junior Data Analyst',                4, 350,
   'Data collection, basic statistics, Excel/spreadsheet tools, SQL basics, and data visualization',
   'https://www.nasscom.in/ssc-qp'),

  ('b1000000-0000-0000-0000-000000000004', 'a1000000-0000-0000-0000-000000000001',
   'SSC/Q0502', 'Data Analyst',                       5, 500,
   'Advanced SQL, Python for data analysis, business intelligence tools, and statistical modelling',
   'https://www.nasscom.in/ssc-qp'),

  ('b1000000-0000-0000-0000-000000000005', 'a1000000-0000-0000-0000-000000000001',
   'SSC/Q0601', 'Junior Network Engineer',            4, 380,
   'Networking fundamentals, TCP/IP, LAN/WAN configuration, and basic cybersecurity',
   'https://www.nasscom.in/ssc-qp'),

  ('b1000000-0000-0000-0000-000000000006', 'a1000000-0000-0000-0000-000000000001',
   'SSC/Q0602', 'Cybersecurity Analyst',              5, 550,
   'Ethical hacking, penetration testing, SIEM tools, incident response, and compliance',
   'https://www.nasscom.in/ssc-qp'),

  ('b1000000-0000-0000-0000-000000000007', 'a1000000-0000-0000-0000-000000000001',
   'SSC/Q0701', 'Junior UI/UX Designer',             4, 320,
   'Design principles, Figma basics, wireframing, user research, and accessibility',
   'https://www.nasscom.in/ssc-qp'),

  ('b1000000-0000-0000-0000-000000000008', 'a1000000-0000-0000-0000-000000000001',
   'SSC/Q0801', 'IT Support Technician',              3, 300,
   'Hardware troubleshooting, OS installation, help desk operations, and customer service',
   'https://www.nasscom.in/ssc-qp');

-- =============================================================================
-- Curriculum Skills per Course (what each course actually teaches)
-- NOTE: embeddings are NULL here — they will be generated by the
--       backend embedding service on first startup (see services/embedding.py)
-- =============================================================================

-- Junior Software Developer (Level 4) skills
INSERT INTO curriculum_skills (course_id, name, category) VALUES
  ('b1000000-0000-0000-0000-000000000001', 'Basic Python Programming',         'Programming'),
  ('b1000000-0000-0000-0000-000000000001', 'HTML5 Fundamentals',               'Web Development'),
  ('b1000000-0000-0000-0000-000000000001', 'CSS3 Styling',                     'Web Development'),
  ('b1000000-0000-0000-0000-000000000001', 'JavaScript Basics',                'Programming'),
  ('b1000000-0000-0000-0000-000000000001', 'Git Version Control',              'DevOps'),
  ('b1000000-0000-0000-0000-000000000001', 'Basic SQL Queries',                'Database'),
  ('b1000000-0000-0000-0000-000000000001', 'Problem Solving',                  'Soft Skills'),
  ('b1000000-0000-0000-0000-000000000001', 'Object Oriented Programming Concepts', 'Programming');

-- Software Developer (Level 5) skills
INSERT INTO curriculum_skills (course_id, name, category) VALUES
  ('b1000000-0000-0000-0000-000000000002', 'React.js Fundamentals',            'Web Development'),
  ('b1000000-0000-0000-0000-000000000002', 'Node.js Backend Development',      'Web Development'),
  ('b1000000-0000-0000-0000-000000000002', 'REST API Design',                  'Backend'),
  ('b1000000-0000-0000-0000-000000000002', 'MySQL Database Design',            'Database'),
  ('b1000000-0000-0000-0000-000000000002', 'Agile and Scrum Methodology',      'Soft Skills'),
  ('b1000000-0000-0000-0000-000000000002', 'Linux Command Line',               'DevOps'),
  ('b1000000-0000-0000-0000-000000000002', 'Unit Testing with Jest',           'Testing'),
  ('b1000000-0000-0000-0000-000000000002', 'Basic Docker Concepts',            'DevOps');

-- Junior Data Analyst (Level 4) skills
INSERT INTO curriculum_skills (course_id, name, category) VALUES
  ('b1000000-0000-0000-0000-000000000003', 'Microsoft Excel Advanced',         'Data Analysis'),
  ('b1000000-0000-0000-0000-000000000003', 'Basic Statistics',                 'Data Science'),
  ('b1000000-0000-0000-0000-000000000003', 'SQL for Data Retrieval',           'Database'),
  ('b1000000-0000-0000-0000-000000000003', 'Data Visualization with Charts',   'Data Analysis'),
  ('b1000000-0000-0000-0000-000000000003', 'Business Communication',           'Soft Skills'),
  ('b1000000-0000-0000-0000-000000000003', 'Google Sheets',                    'Data Analysis');

-- Data Analyst (Level 5) skills
INSERT INTO curriculum_skills (course_id, name, category) VALUES
  ('b1000000-0000-0000-0000-000000000004', 'Python for Data Analysis',         'Data Science'),
  ('b1000000-0000-0000-0000-000000000004', 'Pandas and NumPy',                 'Data Science'),
  ('b1000000-0000-0000-0000-000000000004', 'Power BI Dashboards',              'Data Analysis'),
  ('b1000000-0000-0000-0000-000000000004', 'Advanced SQL and Joins',           'Database'),
  ('b1000000-0000-0000-0000-000000000004', 'Statistical Analysis',             'Data Science'),
  ('b1000000-0000-0000-0000-000000000004', 'Data Cleaning and Preprocessing',  'Data Science'),
  ('b1000000-0000-0000-0000-000000000004', 'Tableau Visualization',            'Data Analysis');

-- =============================================================================
-- Careers (with growth rates sourced from NASSCOM ITBPM 2024 report)
-- =============================================================================

INSERT INTO careers (slug, title, domain, description, difficulty, avg_salary_min, avg_salary_max, growth_rate, nsqf_levels) VALUES
  ('data-engineer',          'Data Engineer',              'Data & AI',
   'Build and maintain data pipelines, warehouses, and processing systems',
   'intermediate', 60000, 180000, 34.5, ARRAY[5,6]),

  ('ml-engineer',            'Machine Learning Engineer',  'Data & AI',
   'Design, train, and deploy machine learning models at scale',
   'advanced', 80000, 250000, 42.0, ARRAY[6,7]),

  ('cloud-architect',        'Cloud Solutions Architect',  'Cloud & DevOps',
   'Design scalable cloud infrastructure on AWS, GCP, or Azure',
   'advanced', 100000, 300000, 38.2, ARRAY[6,7]),

  ('devops-engineer',        'DevOps Engineer',            'Cloud & DevOps',
   'Automate CI/CD pipelines, manage infrastructure as code',
   'intermediate', 70000, 200000, 35.8, ARRAY[5,6]),

  ('fullstack-developer',    'Full Stack Developer',       'Software Development',
   'Build end-to-end web applications with modern frontend and backend tech',
   'intermediate', 50000, 150000, 28.0, ARRAY[4,5,6]),

  ('cybersecurity-analyst',  'Cybersecurity Analyst',      'Security',
   'Monitor, detect, and respond to cyber threats and vulnerabilities',
   'intermediate', 60000, 180000, 31.5, ARRAY[5,6]),

  ('data-scientist',         'Data Scientist',             'Data & AI',
   'Extract insights from complex datasets using statistical and ML methods',
   'advanced', 80000, 230000, 40.1, ARRAY[6,7]),

  ('product-manager',        'Technical Product Manager',  'Management',
   'Define product roadmaps, work with engineering teams to ship features',
   'advanced', 90000, 250000, 25.0, ARRAY[6,7]),

  ('ux-designer',            'UX/UI Designer',             'Design',
   'Design user interfaces and experiences using research and modern design tools',
   'beginner', 40000, 120000, 22.5, ARRAY[4,5]),

  ('backend-developer',      'Backend Developer',          'Software Development',
   'Build server-side applications, APIs, and database architectures',
   'intermediate', 55000, 160000, 27.0, ARRAY[5,6]),

  ('govt-data-analyst',      'Govt Data Analyst (NIC)',    'Government & PSU',
   'Analyse government data for policy decisions at NIC/NIELIT',
   'intermediate', 45000, 90000, 18.0, ARRAY[4,5]),

  ('it-officer-banking',     'IT Officer (Banking Sector)','Government & PSU',
   'Manage IT systems in public sector banks (IBPS IT Officer exam pathway)',
   'intermediate', 50000, 100000, 20.0, ARRAY[5,6]);

-- Career Skills (what each career requires)
INSERT INTO career_skills (career_id, skill_name, importance) VALUES
  -- Data Engineer
  ((SELECT id FROM careers WHERE slug='data-engineer'), 'Apache Spark',        1.0),
  ((SELECT id FROM careers WHERE slug='data-engineer'), 'Apache Kafka',        0.9),
  ((SELECT id FROM careers WHERE slug='data-engineer'), 'dbt',                 0.9),
  ((SELECT id FROM careers WHERE slug='data-engineer'), 'Apache Airflow',      0.85),
  ((SELECT id FROM careers WHERE slug='data-engineer'), 'Python',              1.0),
  ((SELECT id FROM careers WHERE slug='data-engineer'), 'SQL',                 1.0),
  ((SELECT id FROM careers WHERE slug='data-engineer'), 'AWS/GCP/Azure',       0.8),
  ((SELECT id FROM careers WHERE slug='data-engineer'), 'Docker',              0.75),

  -- ML Engineer
  ((SELECT id FROM careers WHERE slug='ml-engineer'), 'PyTorch',              1.0),
  ((SELECT id FROM careers WHERE slug='ml-engineer'), 'TensorFlow',           0.9),
  ((SELECT id FROM careers WHERE slug='ml-engineer'), 'MLflow',               0.85),
  ((SELECT id FROM careers WHERE slug='ml-engineer'), 'Kubernetes',           0.8),
  ((SELECT id FROM careers WHERE slug='ml-engineer'), 'Python',               1.0),
  ((SELECT id FROM careers WHERE slug='ml-engineer'), 'LLM Fine-tuning',      0.75),
  ((SELECT id FROM careers WHERE slug='ml-engineer'), 'Vector Databases',     0.7),

  -- Cloud Architect
  ((SELECT id FROM careers WHERE slug='cloud-architect'), 'AWS Solutions Architect', 1.0),
  ((SELECT id FROM careers WHERE slug='cloud-architect'), 'Terraform',              1.0),
  ((SELECT id FROM careers WHERE slug='cloud-architect'), 'Kubernetes',             0.95),
  ((SELECT id FROM careers WHERE slug='cloud-architect'), 'Networking',             0.9),
  ((SELECT id FROM careers WHERE slug='cloud-architect'), 'Docker',                 0.85),

  -- Full Stack Developer
  ((SELECT id FROM careers WHERE slug='fullstack-developer'), 'React.js',     1.0),
  ((SELECT id FROM careers WHERE slug='fullstack-developer'), 'Node.js',      0.95),
  ((SELECT id FROM careers WHERE slug='fullstack-developer'), 'TypeScript',   0.9),
  ((SELECT id FROM careers WHERE slug='fullstack-developer'), 'PostgreSQL',   0.85),
  ((SELECT id FROM careers WHERE slug='fullstack-developer'), 'REST APIs',    1.0),
  ((SELECT id FROM careers WHERE slug='fullstack-developer'), 'Git',          1.0);

-- =============================================================================
-- Sample Job Postings (Private + Government)
-- In production these come from Crawl4AI scraper
-- =============================================================================

INSERT INTO job_postings (source, sector_type, title, company, location, state, salary_min, salary_max, experience_min, experience_max, url, posted_at, is_processed) VALUES
  -- Private Sector
  ('naukri',   'PRIVATE',    'Data Engineer',                    'Infosys',          'Bengaluru', 'Karnataka', 80000,  150000, 2, 5,  'https://www.naukri.com/job1',  NOW() - INTERVAL '2 days',  TRUE),
  ('naukri',   'PRIVATE',    'ML Engineer',                      'TCS',              'Hyderabad', 'Telangana', 100000, 200000, 3, 7,  'https://www.naukri.com/job2',  NOW() - INTERVAL '1 day',   TRUE),
  ('linkedin', 'PRIVATE',    'Full Stack Developer',             'Razorpay',         'Bengaluru', 'Karnataka', 70000,  130000, 1, 4,  'https://linkedin.com/job3',     NOW() - INTERVAL '3 days',  TRUE),
  ('linkedin', 'PRIVATE',    'DevOps Engineer',                  'Zomato',           'Gurugram',  'Haryana',   90000,  170000, 2, 6,  'https://linkedin.com/job4',     NOW() - INTERVAL '4 days',  TRUE),
  ('naukri',   'PRIVATE',    'Cloud Solutions Architect',        'Wipro',            'Pune',      'Maharashtra',120000,250000, 5, 10, 'https://www.naukri.com/job5',  NOW() - INTERVAL '5 days',  TRUE),
  ('linkedin', 'PRIVATE',    'Data Scientist',                   'Flipkart',         'Bengaluru', 'Karnataka', 100000, 220000, 3, 8,  'https://linkedin.com/job6',     NOW() - INTERVAL '2 days',  TRUE),
  ('naukri',   'PRIVATE',    'Backend Developer (Python)',       'CRED',             'Bengaluru', 'Karnataka', 60000,  120000, 1, 3,  'https://www.naukri.com/job7',  NOW() - INTERVAL '1 day',   TRUE),
  ('linkedin', 'PRIVATE',    'Cybersecurity Analyst',            'HCL Technologies', 'Noida',     'Uttar Pradesh', 65000, 130000, 2, 5, 'https://linkedin.com/job8', NOW() - INTERVAL '6 days',  TRUE),

  -- Government Sector
  ('ncs',      'GOVERNMENT', 'Data Analyst - NIC',               'NIC (Govt of India)', 'New Delhi', 'Delhi',   45000,  75000,  1, 3,  'https://ncs.gov.in/job1',       NOW() - INTERVAL '3 days',  TRUE),
  ('ncs',      'GOVERNMENT', 'IT Officer (IBPS)',                 'Bank of India',       'Mumbai',    'Maharashtra', 50000, 90000, 2, 5, 'https://ncs.gov.in/job2',    NOW() - INTERVAL '5 days',  TRUE),
  ('ssc',      'GOVERNMENT', 'Junior Engineer (Computer)',        'SSC',                 'Pan India', 'All India', 40000, 65000,  0, 2,  'https://ssc.nic.in/je1',        NOW() - INTERVAL '7 days',  TRUE),
  ('ncs',      'GOVERNMENT', 'Software Developer - CDAC',        'CDAC',                'Pune',      'Maharashtra', 55000, 90000, 1, 4, 'https://ncs.gov.in/job4',    NOW() - INTERVAL '4 days',  TRUE),
  ('upsc',     'GOVERNMENT', 'Senior Technical Director - NIC',  'NIC',                 'New Delhi', 'Delhi',     90000, 150000, 8, 15, 'https://upsc.gov.in/job1',      NOW() - INTERVAL '10 days', TRUE),
  ('ncs',      'GOVERNMENT', 'Cybersecurity Analyst - CERT-In',  'CERT-In',             'New Delhi', 'Delhi',     60000, 100000, 2, 6,  'https://ncs.gov.in/job5',       NOW() - INTERVAL '2 days',  TRUE);

-- =============================================================================
-- Skill Demand Stats (computed from above job postings — in production this
-- is done by a nightly background job via ARQ)
-- =============================================================================

INSERT INTO skill_demand_stats (skill_name, sector_type, demand_count, demand_percent, period_date) VALUES
  -- Private sector
  ('Python',              'PRIVATE',    6,  75.0, CURRENT_DATE),
  ('Docker',              'PRIVATE',    5,  62.5, CURRENT_DATE),
  ('Kubernetes',          'PRIVATE',    4,  50.0, CURRENT_DATE),
  ('Apache Spark',        'PRIVATE',    3,  37.5, CURRENT_DATE),
  ('React.js',            'PRIVATE',    4,  50.0, CURRENT_DATE),
  ('TypeScript',          'PRIVATE',    4,  50.0, CURRENT_DATE),
  ('AWS',                 'PRIVATE',    5,  62.5, CURRENT_DATE),
  ('LLM Fine-tuning',     'PRIVATE',    3,  37.5, CURRENT_DATE),
  ('dbt',                 'PRIVATE',    2,  25.0, CURRENT_DATE),
  ('MLflow',              'PRIVATE',    2,  25.0, CURRENT_DATE),
  -- Government sector
  ('Python',              'GOVERNMENT', 4,  66.7, CURRENT_DATE),
  ('SQL',                 'GOVERNMENT', 5,  83.3, CURRENT_DATE),
  ('Cybersecurity',       'GOVERNMENT', 3,  50.0, CURRENT_DATE),
  ('Linux',               'GOVERNMENT', 3,  50.0, CURRENT_DATE),
  ('Networking',          'GOVERNMENT', 2,  33.3, CURRENT_DATE),
  ('Cloud Computing',     'GOVERNMENT', 2,  33.3, CURRENT_DATE),
  ('Java',                'GOVERNMENT', 2,  33.3, CURRENT_DATE);
